apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-acl
data:
  users.acl: |
    user admin on >__ADMIN_PASSWORD__ ~* &* +@all
    user replication on >__REPLICATION_PASSWORD__ +psync +replconf +ping
    user default on >__DEFAULT_PASSWORD__ ~* &* +@all -@dangerous